server:
  port: 8081
swagger:
  enabled: true

#  当HTTP状态码为4xx时直接抛出异常
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  #  关闭默认的静态资源路径映射
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:h2:./test.db;AUTO_SERVER=TRUE;MODE=MYSQL;
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
#      ddl-auto: none
#      dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
#      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: false


