package org.example.steam.codec;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom.proto

// Protobuf Java Version: 3.25.1
public final class Custom {
  private Custom() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string device_friendly_name = 1;</code>
     * @return Whether the deviceFriendlyName field is set.
     */
    boolean hasDeviceFriendlyName();
    /**
     * <code>optional string device_friendly_name = 1;</code>
     * @return The deviceFriendlyName.
     */
    java.lang.String getDeviceFriendlyName();
    /**
     * <code>optional string device_friendly_name = 1;</code>
     * @return The bytes for deviceFriendlyName.
     */
    com.google.protobuf.ByteString
        getDeviceFriendlyNameBytes();

    /**
     * <code>optional string account_name = 2;</code>
     * @return Whether the accountName field is set.
     */
    boolean hasAccountName();
    /**
     * <code>optional string account_name = 2;</code>
     * @return The accountName.
     */
    java.lang.String getAccountName();
    /**
     * <code>optional string account_name = 2;</code>
     * @return The bytes for accountName.
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    /**
     * <code>optional string encrypted_password = 3 [(.description) = "password, RSA encrypted client side"];</code>
     * @return Whether the encryptedPassword field is set.
     */
    boolean hasEncryptedPassword();
    /**
     * <code>optional string encrypted_password = 3 [(.description) = "password, RSA encrypted client side"];</code>
     * @return The encryptedPassword.
     */
    java.lang.String getEncryptedPassword();
    /**
     * <code>optional string encrypted_password = 3 [(.description) = "password, RSA encrypted client side"];</code>
     * @return The bytes for encryptedPassword.
     */
    com.google.protobuf.ByteString
        getEncryptedPasswordBytes();

    /**
     * <code>optional uint64 encryption_timestamp = 4 [(.description) = "timestamp to map to a key - STime"];</code>
     * @return Whether the encryptionTimestamp field is set.
     */
    boolean hasEncryptionTimestamp();
    /**
     * <code>optional uint64 encryption_timestamp = 4 [(.description) = "timestamp to map to a key - STime"];</code>
     * @return The encryptionTimestamp.
     */
    long getEncryptionTimestamp();

    /**
     * <code>optional bool remember_login = 5 [(.description) = "deprecated"];</code>
     * @return Whether the rememberLogin field is set.
     */
    boolean hasRememberLogin();
    /**
     * <code>optional bool remember_login = 5 [(.description) = "deprecated"];</code>
     * @return The rememberLogin.
     */
    boolean getRememberLogin();

    /**
     * <code>optional .EAuthTokenPlatformType platform_type = 6 [default = k_EAuthTokenPlatformType_Unknown];</code>
     * @return Whether the platformType field is set.
     */
    boolean hasPlatformType();
    /**
     * <code>optional .EAuthTokenPlatformType platform_type = 6 [default = k_EAuthTokenPlatformType_Unknown];</code>
     * @return The platformType.
     */
    SteammessagesAuthSteamclient.EAuthTokenPlatformType getPlatformType();

    /**
     * <code>optional .ESessionPersistence persistence = 7 [default = k_ESessionPersistence_Persistent, (.description) = "whether we are requesting a persistent or an ephemeral session"];</code>
     * @return Whether the persistence field is set.
     */
    boolean hasPersistence();
    /**
     * <code>optional .ESessionPersistence persistence = 7 [default = k_ESessionPersistence_Persistent, (.description) = "whether we are requesting a persistent or an ephemeral session"];</code>
     * @return The persistence.
     */
    Enums.ESessionPersistence getPersistence();

    /**
     * <code>optional string website_id = 8 [default = "Unknown", (.description) = "(EMachineAuthWebDomain) identifier of client requesting auth"];</code>
     * @return Whether the websiteId field is set.
     */
    boolean hasWebsiteId();
    /**
     * <code>optional string website_id = 8 [default = "Unknown", (.description) = "(EMachineAuthWebDomain) identifier of client requesting auth"];</code>
     * @return The websiteId.
     */
    java.lang.String getWebsiteId();
    /**
     * <code>optional string website_id = 8 [default = "Unknown", (.description) = "(EMachineAuthWebDomain) identifier of client requesting auth"];</code>
     * @return The bytes for websiteId.
     */
    com.google.protobuf.ByteString
        getWebsiteIdBytes();

    /**
     * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
     * @return Whether the deviceDetails field is set.
     */
    boolean hasDeviceDetails();
    /**
     * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
     * @return The deviceDetails.
     */
    SteammessagesAuthSteamclient.CAuthentication_DeviceDetails getDeviceDetails();
    /**
     * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
     */
    SteammessagesAuthSteamclient.CAuthentication_DeviceDetailsOrBuilder getDeviceDetailsOrBuilder();

    /**
     * <code>optional bytes guard_data = 10 [(.description) = "steam guard data for client login"];</code>
     * @return Whether the guardData field is set.
     */
    boolean hasGuardData();
    /**
     * <code>optional bytes guard_data = 10 [(.description) = "steam guard data for client login"];</code>
     * @return The guardData.
     */
    com.google.protobuf.ByteString getGuardData();

    /**
     * <code>optional uint32 language = 11;</code>
     * @return Whether the language field is set.
     */
    boolean hasLanguage();
    /**
     * <code>optional uint32 language = 11;</code>
     * @return The language.
     */
    int getLanguage();

    /**
     * <code>optional int32 qos_level = 12 [default = 2, (.description) = "[ENetQOSLevel] client-specified priority for this auth attempt"];</code>
     * @return Whether the qosLevel field is set.
     */
    boolean hasQosLevel();
    /**
     * <code>optional int32 qos_level = 12 [default = 2, (.description) = "[ENetQOSLevel] client-specified priority for this auth attempt"];</code>
     * @return The qosLevel.
     */
    int getQosLevel();
  }
  /**
   * Protobuf type {@code CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData}
   */
  public static final class CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData)
      CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData.newBuilder() to construct.
    private CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData() {
      deviceFriendlyName_ = "";
      accountName_ = "";
      encryptedPassword_ = "";
      platformType_ = 0;
      persistence_ = 1;
      websiteId_ = "Unknown";
      guardData_ = com.google.protobuf.ByteString.EMPTY;
      qosLevel_ = 2;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Custom.internal_static_CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Custom.internal_static_CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData.class, Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData.Builder.class);
    }

    private int bitField0_;
    public static final int DEVICE_FRIENDLY_NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object deviceFriendlyName_ = "";
    /**
     * <code>optional string device_friendly_name = 1;</code>
     * @return Whether the deviceFriendlyName field is set.
     */
    @java.lang.Override
    public boolean hasDeviceFriendlyName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string device_friendly_name = 1;</code>
     * @return The deviceFriendlyName.
     */
    @java.lang.Override
    public java.lang.String getDeviceFriendlyName() {
      java.lang.Object ref = deviceFriendlyName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceFriendlyName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_friendly_name = 1;</code>
     * @return The bytes for deviceFriendlyName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceFriendlyNameBytes() {
      java.lang.Object ref = deviceFriendlyName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceFriendlyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object accountName_ = "";
    /**
     * <code>optional string account_name = 2;</code>
     * @return Whether the accountName field is set.
     */
    @java.lang.Override
    public boolean hasAccountName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string account_name = 2;</code>
     * @return The accountName.
     */
    @java.lang.Override
    public java.lang.String getAccountName() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accountName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string account_name = 2;</code>
     * @return The bytes for accountName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPTED_PASSWORD_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object encryptedPassword_ = "";
    /**
     * <code>optional string encrypted_password = 3 [(.description) = "password, RSA encrypted client side"];</code>
     * @return Whether the encryptedPassword field is set.
     */
    @java.lang.Override
    public boolean hasEncryptedPassword() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string encrypted_password = 3 [(.description) = "password, RSA encrypted client side"];</code>
     * @return The encryptedPassword.
     */
    @java.lang.Override
    public java.lang.String getEncryptedPassword() {
      java.lang.Object ref = encryptedPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          encryptedPassword_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string encrypted_password = 3 [(.description) = "password, RSA encrypted client side"];</code>
     * @return The bytes for encryptedPassword.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEncryptedPasswordBytes() {
      java.lang.Object ref = encryptedPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encryptedPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPTION_TIMESTAMP_FIELD_NUMBER = 4;
    private long encryptionTimestamp_ = 0L;
    /**
     * <code>optional uint64 encryption_timestamp = 4 [(.description) = "timestamp to map to a key - STime"];</code>
     * @return Whether the encryptionTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasEncryptionTimestamp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint64 encryption_timestamp = 4 [(.description) = "timestamp to map to a key - STime"];</code>
     * @return The encryptionTimestamp.
     */
    @java.lang.Override
    public long getEncryptionTimestamp() {
      return encryptionTimestamp_;
    }

    public static final int REMEMBER_LOGIN_FIELD_NUMBER = 5;
    private boolean rememberLogin_ = false;
    /**
     * <code>optional bool remember_login = 5 [(.description) = "deprecated"];</code>
     * @return Whether the rememberLogin field is set.
     */
    @java.lang.Override
    public boolean hasRememberLogin() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bool remember_login = 5 [(.description) = "deprecated"];</code>
     * @return The rememberLogin.
     */
    @java.lang.Override
    public boolean getRememberLogin() {
      return rememberLogin_;
    }

    public static final int PLATFORM_TYPE_FIELD_NUMBER = 6;
    private int platformType_ = 0;
    /**
     * <code>optional .EAuthTokenPlatformType platform_type = 6 [default = k_EAuthTokenPlatformType_Unknown];</code>
     * @return Whether the platformType field is set.
     */
    @java.lang.Override public boolean hasPlatformType() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .EAuthTokenPlatformType platform_type = 6 [default = k_EAuthTokenPlatformType_Unknown];</code>
     * @return The platformType.
     */
    @java.lang.Override public SteammessagesAuthSteamclient.EAuthTokenPlatformType getPlatformType() {
      SteammessagesAuthSteamclient.EAuthTokenPlatformType result = SteammessagesAuthSteamclient.EAuthTokenPlatformType.forNumber(platformType_);
      return result == null ? SteammessagesAuthSteamclient.EAuthTokenPlatformType.k_EAuthTokenPlatformType_Unknown : result;
    }

    public static final int PERSISTENCE_FIELD_NUMBER = 7;
    private int persistence_ = 1;
    /**
     * <code>optional .ESessionPersistence persistence = 7 [default = k_ESessionPersistence_Persistent, (.description) = "whether we are requesting a persistent or an ephemeral session"];</code>
     * @return Whether the persistence field is set.
     */
    @java.lang.Override public boolean hasPersistence() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .ESessionPersistence persistence = 7 [default = k_ESessionPersistence_Persistent, (.description) = "whether we are requesting a persistent or an ephemeral session"];</code>
     * @return The persistence.
     */
    @java.lang.Override public Enums.ESessionPersistence getPersistence() {
      Enums.ESessionPersistence result = Enums.ESessionPersistence.forNumber(persistence_);
      return result == null ? Enums.ESessionPersistence.k_ESessionPersistence_Persistent : result;
    }

    public static final int WEBSITE_ID_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object websiteId_ = "Unknown";
    /**
     * <code>optional string website_id = 8 [default = "Unknown", (.description) = "(EMachineAuthWebDomain) identifier of client requesting auth"];</code>
     * @return Whether the websiteId field is set.
     */
    @java.lang.Override
    public boolean hasWebsiteId() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string website_id = 8 [default = "Unknown", (.description) = "(EMachineAuthWebDomain) identifier of client requesting auth"];</code>
     * @return The websiteId.
     */
    @java.lang.Override
    public java.lang.String getWebsiteId() {
      java.lang.Object ref = websiteId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          websiteId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string website_id = 8 [default = "Unknown", (.description) = "(EMachineAuthWebDomain) identifier of client requesting auth"];</code>
     * @return The bytes for websiteId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWebsiteIdBytes() {
      java.lang.Object ref = websiteId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        websiteId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_DETAILS_FIELD_NUMBER = 9;
    private SteammessagesAuthSteamclient.CAuthentication_DeviceDetails deviceDetails_;
    /**
     * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
     * @return Whether the deviceDetails field is set.
     */
    @java.lang.Override
    public boolean hasDeviceDetails() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
     * @return The deviceDetails.
     */
    @java.lang.Override
    public SteammessagesAuthSteamclient.CAuthentication_DeviceDetails getDeviceDetails() {
      return deviceDetails_ == null ? SteammessagesAuthSteamclient.CAuthentication_DeviceDetails.getDefaultInstance() : deviceDetails_;
    }
    /**
     * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
     */
    @java.lang.Override
    public SteammessagesAuthSteamclient.CAuthentication_DeviceDetailsOrBuilder getDeviceDetailsOrBuilder() {
      return deviceDetails_ == null ? SteammessagesAuthSteamclient.CAuthentication_DeviceDetails.getDefaultInstance() : deviceDetails_;
    }

    public static final int GUARD_DATA_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString guardData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes guard_data = 10 [(.description) = "steam guard data for client login"];</code>
     * @return Whether the guardData field is set.
     */
    @java.lang.Override
    public boolean hasGuardData() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional bytes guard_data = 10 [(.description) = "steam guard data for client login"];</code>
     * @return The guardData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGuardData() {
      return guardData_;
    }

    public static final int LANGUAGE_FIELD_NUMBER = 11;
    private int language_ = 0;
    /**
     * <code>optional uint32 language = 11;</code>
     * @return Whether the language field is set.
     */
    @java.lang.Override
    public boolean hasLanguage() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional uint32 language = 11;</code>
     * @return The language.
     */
    @java.lang.Override
    public int getLanguage() {
      return language_;
    }

    public static final int QOS_LEVEL_FIELD_NUMBER = 12;
    private int qosLevel_ = 2;
    /**
     * <code>optional int32 qos_level = 12 [default = 2, (.description) = "[ENetQOSLevel] client-specified priority for this auth attempt"];</code>
     * @return Whether the qosLevel field is set.
     */
    @java.lang.Override
    public boolean hasQosLevel() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional int32 qos_level = 12 [default = 2, (.description) = "[ENetQOSLevel] client-specified priority for this auth attempt"];</code>
     * @return The qosLevel.
     */
    @java.lang.Override
    public int getQosLevel() {
      return qosLevel_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceFriendlyName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accountName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, encryptedPassword_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt64(4, encryptionTimestamp_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(5, rememberLogin_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeEnum(6, platformType_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeEnum(7, persistence_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, websiteId_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeMessage(9, getDeviceDetails());
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeBytes(10, guardData_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeUInt32(11, language_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        output.writeInt32(12, qosLevel_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceFriendlyName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accountName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, encryptedPassword_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, encryptionTimestamp_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, rememberLogin_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, platformType_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, persistence_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, websiteId_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getDeviceDetails());
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, guardData_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, language_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, qosLevel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData)) {
        return super.equals(obj);
      }
      Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData other = (Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData) obj;

      if (hasDeviceFriendlyName() != other.hasDeviceFriendlyName()) return false;
      if (hasDeviceFriendlyName()) {
        if (!getDeviceFriendlyName()
            .equals(other.getDeviceFriendlyName())) return false;
      }
      if (hasAccountName() != other.hasAccountName()) return false;
      if (hasAccountName()) {
        if (!getAccountName()
            .equals(other.getAccountName())) return false;
      }
      if (hasEncryptedPassword() != other.hasEncryptedPassword()) return false;
      if (hasEncryptedPassword()) {
        if (!getEncryptedPassword()
            .equals(other.getEncryptedPassword())) return false;
      }
      if (hasEncryptionTimestamp() != other.hasEncryptionTimestamp()) return false;
      if (hasEncryptionTimestamp()) {
        if (getEncryptionTimestamp()
            != other.getEncryptionTimestamp()) return false;
      }
      if (hasRememberLogin() != other.hasRememberLogin()) return false;
      if (hasRememberLogin()) {
        if (getRememberLogin()
            != other.getRememberLogin()) return false;
      }
      if (hasPlatformType() != other.hasPlatformType()) return false;
      if (hasPlatformType()) {
        if (platformType_ != other.platformType_) return false;
      }
      if (hasPersistence() != other.hasPersistence()) return false;
      if (hasPersistence()) {
        if (persistence_ != other.persistence_) return false;
      }
      if (hasWebsiteId() != other.hasWebsiteId()) return false;
      if (hasWebsiteId()) {
        if (!getWebsiteId()
            .equals(other.getWebsiteId())) return false;
      }
      if (hasDeviceDetails() != other.hasDeviceDetails()) return false;
      if (hasDeviceDetails()) {
        if (!getDeviceDetails()
            .equals(other.getDeviceDetails())) return false;
      }
      if (hasGuardData() != other.hasGuardData()) return false;
      if (hasGuardData()) {
        if (!getGuardData()
            .equals(other.getGuardData())) return false;
      }
      if (hasLanguage() != other.hasLanguage()) return false;
      if (hasLanguage()) {
        if (getLanguage()
            != other.getLanguage()) return false;
      }
      if (hasQosLevel() != other.hasQosLevel()) return false;
      if (hasQosLevel()) {
        if (getQosLevel()
            != other.getQosLevel()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDeviceFriendlyName()) {
        hash = (37 * hash) + DEVICE_FRIENDLY_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceFriendlyName().hashCode();
      }
      if (hasAccountName()) {
        hash = (37 * hash) + ACCOUNT_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getAccountName().hashCode();
      }
      if (hasEncryptedPassword()) {
        hash = (37 * hash) + ENCRYPTED_PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getEncryptedPassword().hashCode();
      }
      if (hasEncryptionTimestamp()) {
        hash = (37 * hash) + ENCRYPTION_TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEncryptionTimestamp());
      }
      if (hasRememberLogin()) {
        hash = (37 * hash) + REMEMBER_LOGIN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRememberLogin());
      }
      if (hasPlatformType()) {
        hash = (37 * hash) + PLATFORM_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + platformType_;
      }
      if (hasPersistence()) {
        hash = (37 * hash) + PERSISTENCE_FIELD_NUMBER;
        hash = (53 * hash) + persistence_;
      }
      if (hasWebsiteId()) {
        hash = (37 * hash) + WEBSITE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getWebsiteId().hashCode();
      }
      if (hasDeviceDetails()) {
        hash = (37 * hash) + DEVICE_DETAILS_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceDetails().hashCode();
      }
      if (hasGuardData()) {
        hash = (37 * hash) + GUARD_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getGuardData().hashCode();
      }
      if (hasLanguage()) {
        hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
        hash = (53 * hash) + getLanguage();
      }
      if (hasQosLevel()) {
        hash = (37 * hash) + QOS_LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getQosLevel();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData)
        Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Custom.internal_static_CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Custom.internal_static_CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData.class, Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData.Builder.class);
      }

      // Construct using Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDeviceDetailsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        deviceFriendlyName_ = "";
        accountName_ = "";
        encryptedPassword_ = "";
        encryptionTimestamp_ = 0L;
        rememberLogin_ = false;
        platformType_ = 0;
        persistence_ = 1;
        websiteId_ = "Unknown";
        deviceDetails_ = null;
        if (deviceDetailsBuilder_ != null) {
          deviceDetailsBuilder_.dispose();
          deviceDetailsBuilder_ = null;
        }
        guardData_ = com.google.protobuf.ByteString.EMPTY;
        language_ = 0;
        qosLevel_ = 2;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Custom.internal_static_CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData_descriptor;
      }

      @java.lang.Override
      public Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData getDefaultInstanceForType() {
        return Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData.getDefaultInstance();
      }

      @java.lang.Override
      public Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData build() {
        Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData buildPartial() {
        Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData result = new Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.deviceFriendlyName_ = deviceFriendlyName_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.accountName_ = accountName_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.encryptedPassword_ = encryptedPassword_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.encryptionTimestamp_ = encryptionTimestamp_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.rememberLogin_ = rememberLogin_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.platformType_ = platformType_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.persistence_ = persistence_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.websiteId_ = websiteId_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.deviceDetails_ = deviceDetailsBuilder_ == null
              ? deviceDetails_
              : deviceDetailsBuilder_.build();
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.guardData_ = guardData_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.language_ = language_;
          to_bitField0_ |= 0x00000400;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.qosLevel_ = qosLevel_;
          to_bitField0_ |= 0x00000800;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData) {
          return mergeFrom((Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData other) {
        if (other == Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData.getDefaultInstance()) return this;
        if (other.hasDeviceFriendlyName()) {
          deviceFriendlyName_ = other.deviceFriendlyName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasAccountName()) {
          accountName_ = other.accountName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasEncryptedPassword()) {
          encryptedPassword_ = other.encryptedPassword_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasEncryptionTimestamp()) {
          setEncryptionTimestamp(other.getEncryptionTimestamp());
        }
        if (other.hasRememberLogin()) {
          setRememberLogin(other.getRememberLogin());
        }
        if (other.hasPlatformType()) {
          setPlatformType(other.getPlatformType());
        }
        if (other.hasPersistence()) {
          setPersistence(other.getPersistence());
        }
        if (other.hasWebsiteId()) {
          websiteId_ = other.websiteId_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (other.hasDeviceDetails()) {
          mergeDeviceDetails(other.getDeviceDetails());
        }
        if (other.hasGuardData()) {
          setGuardData(other.getGuardData());
        }
        if (other.hasLanguage()) {
          setLanguage(other.getLanguage());
        }
        if (other.hasQosLevel()) {
          setQosLevel(other.getQosLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                deviceFriendlyName_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                accountName_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                encryptedPassword_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                encryptionTimestamp_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                rememberLogin_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                int tmpRaw = input.readEnum();
                SteammessagesAuthSteamclient.EAuthTokenPlatformType tmpValue =
                    SteammessagesAuthSteamclient.EAuthTokenPlatformType.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(6, tmpRaw);
                } else {
                  platformType_ = tmpRaw;
                  bitField0_ |= 0x00000020;
                }
                break;
              } // case 48
              case 56: {
                int tmpRaw = input.readEnum();
                Enums.ESessionPersistence tmpValue =
                    Enums.ESessionPersistence.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(7, tmpRaw);
                } else {
                  persistence_ = tmpRaw;
                  bitField0_ |= 0x00000040;
                }
                break;
              } // case 56
              case 66: {
                websiteId_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                input.readMessage(
                    getDeviceDetailsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                guardData_ = input.readBytes();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 88: {
                language_ = input.readUInt32();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              case 96: {
                qosLevel_ = input.readInt32();
                bitField0_ |= 0x00000800;
                break;
              } // case 96
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object deviceFriendlyName_ = "";
      /**
       * <code>optional string device_friendly_name = 1;</code>
       * @return Whether the deviceFriendlyName field is set.
       */
      public boolean hasDeviceFriendlyName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string device_friendly_name = 1;</code>
       * @return The deviceFriendlyName.
       */
      public java.lang.String getDeviceFriendlyName() {
        java.lang.Object ref = deviceFriendlyName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceFriendlyName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_friendly_name = 1;</code>
       * @return The bytes for deviceFriendlyName.
       */
      public com.google.protobuf.ByteString
          getDeviceFriendlyNameBytes() {
        java.lang.Object ref = deviceFriendlyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceFriendlyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_friendly_name = 1;</code>
       * @param value The deviceFriendlyName to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceFriendlyName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        deviceFriendlyName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_friendly_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceFriendlyName() {
        deviceFriendlyName_ = getDefaultInstance().getDeviceFriendlyName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_friendly_name = 1;</code>
       * @param value The bytes for deviceFriendlyName to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceFriendlyNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        deviceFriendlyName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object accountName_ = "";
      /**
       * <code>optional string account_name = 2;</code>
       * @return Whether the accountName field is set.
       */
      public boolean hasAccountName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string account_name = 2;</code>
       * @return The accountName.
       */
      public java.lang.String getAccountName() {
        java.lang.Object ref = accountName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            accountName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string account_name = 2;</code>
       * @return The bytes for accountName.
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        java.lang.Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account_name = 2;</code>
       * @param value The accountName to set.
       * @return This builder for chaining.
       */
      public Builder setAccountName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        accountName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string account_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountName() {
        accountName_ = getDefaultInstance().getAccountName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string account_name = 2;</code>
       * @param value The bytes for accountName to set.
       * @return This builder for chaining.
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        accountName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object encryptedPassword_ = "";
      /**
       * <code>optional string encrypted_password = 3 [(.description) = "password, RSA encrypted client side"];</code>
       * @return Whether the encryptedPassword field is set.
       */
      public boolean hasEncryptedPassword() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string encrypted_password = 3 [(.description) = "password, RSA encrypted client side"];</code>
       * @return The encryptedPassword.
       */
      public java.lang.String getEncryptedPassword() {
        java.lang.Object ref = encryptedPassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            encryptedPassword_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string encrypted_password = 3 [(.description) = "password, RSA encrypted client side"];</code>
       * @return The bytes for encryptedPassword.
       */
      public com.google.protobuf.ByteString
          getEncryptedPasswordBytes() {
        java.lang.Object ref = encryptedPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          encryptedPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string encrypted_password = 3 [(.description) = "password, RSA encrypted client side"];</code>
       * @param value The encryptedPassword to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedPassword(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        encryptedPassword_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string encrypted_password = 3 [(.description) = "password, RSA encrypted client side"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptedPassword() {
        encryptedPassword_ = getDefaultInstance().getEncryptedPassword();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string encrypted_password = 3 [(.description) = "password, RSA encrypted client side"];</code>
       * @param value The bytes for encryptedPassword to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        encryptedPassword_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private long encryptionTimestamp_ ;
      /**
       * <code>optional uint64 encryption_timestamp = 4 [(.description) = "timestamp to map to a key - STime"];</code>
       * @return Whether the encryptionTimestamp field is set.
       */
      @java.lang.Override
      public boolean hasEncryptionTimestamp() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint64 encryption_timestamp = 4 [(.description) = "timestamp to map to a key - STime"];</code>
       * @return The encryptionTimestamp.
       */
      @java.lang.Override
      public long getEncryptionTimestamp() {
        return encryptionTimestamp_;
      }
      /**
       * <code>optional uint64 encryption_timestamp = 4 [(.description) = "timestamp to map to a key - STime"];</code>
       * @param value The encryptionTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptionTimestamp(long value) {

        encryptionTimestamp_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 encryption_timestamp = 4 [(.description) = "timestamp to map to a key - STime"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptionTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        encryptionTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private boolean rememberLogin_ ;
      /**
       * <code>optional bool remember_login = 5 [(.description) = "deprecated"];</code>
       * @return Whether the rememberLogin field is set.
       */
      @java.lang.Override
      public boolean hasRememberLogin() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bool remember_login = 5 [(.description) = "deprecated"];</code>
       * @return The rememberLogin.
       */
      @java.lang.Override
      public boolean getRememberLogin() {
        return rememberLogin_;
      }
      /**
       * <code>optional bool remember_login = 5 [(.description) = "deprecated"];</code>
       * @param value The rememberLogin to set.
       * @return This builder for chaining.
       */
      public Builder setRememberLogin(boolean value) {

        rememberLogin_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool remember_login = 5 [(.description) = "deprecated"];</code>
       * @return This builder for chaining.
       */
      public Builder clearRememberLogin() {
        bitField0_ = (bitField0_ & ~0x00000010);
        rememberLogin_ = false;
        onChanged();
        return this;
      }

      private int platformType_ = 0;
      /**
       * <code>optional .EAuthTokenPlatformType platform_type = 6 [default = k_EAuthTokenPlatformType_Unknown];</code>
       * @return Whether the platformType field is set.
       */
      @java.lang.Override public boolean hasPlatformType() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional .EAuthTokenPlatformType platform_type = 6 [default = k_EAuthTokenPlatformType_Unknown];</code>
       * @return The platformType.
       */
      @java.lang.Override
      public SteammessagesAuthSteamclient.EAuthTokenPlatformType getPlatformType() {
        SteammessagesAuthSteamclient.EAuthTokenPlatformType result = SteammessagesAuthSteamclient.EAuthTokenPlatformType.forNumber(platformType_);
        return result == null ? SteammessagesAuthSteamclient.EAuthTokenPlatformType.k_EAuthTokenPlatformType_Unknown : result;
      }
      /**
       * <code>optional .EAuthTokenPlatformType platform_type = 6 [default = k_EAuthTokenPlatformType_Unknown];</code>
       * @param value The platformType to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformType(SteammessagesAuthSteamclient.EAuthTokenPlatformType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        platformType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .EAuthTokenPlatformType platform_type = 6 [default = k_EAuthTokenPlatformType_Unknown];</code>
       * @return This builder for chaining.
       */
      public Builder clearPlatformType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        platformType_ = 0;
        onChanged();
        return this;
      }

      private int persistence_ = 1;
      /**
       * <code>optional .ESessionPersistence persistence = 7 [default = k_ESessionPersistence_Persistent, (.description) = "whether we are requesting a persistent or an ephemeral session"];</code>
       * @return Whether the persistence field is set.
       */
      @java.lang.Override public boolean hasPersistence() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional .ESessionPersistence persistence = 7 [default = k_ESessionPersistence_Persistent, (.description) = "whether we are requesting a persistent or an ephemeral session"];</code>
       * @return The persistence.
       */
      @java.lang.Override
      public Enums.ESessionPersistence getPersistence() {
        Enums.ESessionPersistence result = Enums.ESessionPersistence.forNumber(persistence_);
        return result == null ? Enums.ESessionPersistence.k_ESessionPersistence_Persistent : result;
      }
      /**
       * <code>optional .ESessionPersistence persistence = 7 [default = k_ESessionPersistence_Persistent, (.description) = "whether we are requesting a persistent or an ephemeral session"];</code>
       * @param value The persistence to set.
       * @return This builder for chaining.
       */
      public Builder setPersistence(Enums.ESessionPersistence value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        persistence_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .ESessionPersistence persistence = 7 [default = k_ESessionPersistence_Persistent, (.description) = "whether we are requesting a persistent or an ephemeral session"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPersistence() {
        bitField0_ = (bitField0_ & ~0x00000040);
        persistence_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object websiteId_ = "Unknown";
      /**
       * <code>optional string website_id = 8 [default = "Unknown", (.description) = "(EMachineAuthWebDomain) identifier of client requesting auth"];</code>
       * @return Whether the websiteId field is set.
       */
      public boolean hasWebsiteId() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional string website_id = 8 [default = "Unknown", (.description) = "(EMachineAuthWebDomain) identifier of client requesting auth"];</code>
       * @return The websiteId.
       */
      public java.lang.String getWebsiteId() {
        java.lang.Object ref = websiteId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            websiteId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string website_id = 8 [default = "Unknown", (.description) = "(EMachineAuthWebDomain) identifier of client requesting auth"];</code>
       * @return The bytes for websiteId.
       */
      public com.google.protobuf.ByteString
          getWebsiteIdBytes() {
        java.lang.Object ref = websiteId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          websiteId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string website_id = 8 [default = "Unknown", (.description) = "(EMachineAuthWebDomain) identifier of client requesting auth"];</code>
       * @param value The websiteId to set.
       * @return This builder for chaining.
       */
      public Builder setWebsiteId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        websiteId_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional string website_id = 8 [default = "Unknown", (.description) = "(EMachineAuthWebDomain) identifier of client requesting auth"];</code>
       * @return This builder for chaining.
       */
      public Builder clearWebsiteId() {
        websiteId_ = getDefaultInstance().getWebsiteId();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>optional string website_id = 8 [default = "Unknown", (.description) = "(EMachineAuthWebDomain) identifier of client requesting auth"];</code>
       * @param value The bytes for websiteId to set.
       * @return This builder for chaining.
       */
      public Builder setWebsiteIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        websiteId_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private SteammessagesAuthSteamclient.CAuthentication_DeviceDetails deviceDetails_;
      private com.google.protobuf.SingleFieldBuilderV3<
          SteammessagesAuthSteamclient.CAuthentication_DeviceDetails, SteammessagesAuthSteamclient.CAuthentication_DeviceDetails.Builder, SteammessagesAuthSteamclient.CAuthentication_DeviceDetailsOrBuilder> deviceDetailsBuilder_;
      /**
       * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
       * @return Whether the deviceDetails field is set.
       */
      public boolean hasDeviceDetails() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
       * @return The deviceDetails.
       */
      public SteammessagesAuthSteamclient.CAuthentication_DeviceDetails getDeviceDetails() {
        if (deviceDetailsBuilder_ == null) {
          return deviceDetails_ == null ? SteammessagesAuthSteamclient.CAuthentication_DeviceDetails.getDefaultInstance() : deviceDetails_;
        } else {
          return deviceDetailsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
       */
      public Builder setDeviceDetails(SteammessagesAuthSteamclient.CAuthentication_DeviceDetails value) {
        if (deviceDetailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deviceDetails_ = value;
        } else {
          deviceDetailsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
       */
      public Builder setDeviceDetails(
          SteammessagesAuthSteamclient.CAuthentication_DeviceDetails.Builder builderForValue) {
        if (deviceDetailsBuilder_ == null) {
          deviceDetails_ = builderForValue.build();
        } else {
          deviceDetailsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
       */
      public Builder mergeDeviceDetails(SteammessagesAuthSteamclient.CAuthentication_DeviceDetails value) {
        if (deviceDetailsBuilder_ == null) {
          if (((bitField0_ & 0x00000100) != 0) &&
            deviceDetails_ != null &&
            deviceDetails_ != SteammessagesAuthSteamclient.CAuthentication_DeviceDetails.getDefaultInstance()) {
            getDeviceDetailsBuilder().mergeFrom(value);
          } else {
            deviceDetails_ = value;
          }
        } else {
          deviceDetailsBuilder_.mergeFrom(value);
        }
        if (deviceDetails_ != null) {
          bitField0_ |= 0x00000100;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
       */
      public Builder clearDeviceDetails() {
        bitField0_ = (bitField0_ & ~0x00000100);
        deviceDetails_ = null;
        if (deviceDetailsBuilder_ != null) {
          deviceDetailsBuilder_.dispose();
          deviceDetailsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
       */
      public SteammessagesAuthSteamclient.CAuthentication_DeviceDetails.Builder getDeviceDetailsBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getDeviceDetailsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
       */
      public SteammessagesAuthSteamclient.CAuthentication_DeviceDetailsOrBuilder getDeviceDetailsOrBuilder() {
        if (deviceDetailsBuilder_ != null) {
          return deviceDetailsBuilder_.getMessageOrBuilder();
        } else {
          return deviceDetails_ == null ?
              SteammessagesAuthSteamclient.CAuthentication_DeviceDetails.getDefaultInstance() : deviceDetails_;
        }
      }
      /**
       * <code>optional .CAuthentication_DeviceDetails device_details = 9 [(.description) = "User-supplied details about the device attempting to sign in"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          SteammessagesAuthSteamclient.CAuthentication_DeviceDetails, SteammessagesAuthSteamclient.CAuthentication_DeviceDetails.Builder, SteammessagesAuthSteamclient.CAuthentication_DeviceDetailsOrBuilder> 
          getDeviceDetailsFieldBuilder() {
        if (deviceDetailsBuilder_ == null) {
          deviceDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              SteammessagesAuthSteamclient.CAuthentication_DeviceDetails, SteammessagesAuthSteamclient.CAuthentication_DeviceDetails.Builder, SteammessagesAuthSteamclient.CAuthentication_DeviceDetailsOrBuilder>(
                  getDeviceDetails(),
                  getParentForChildren(),
                  isClean());
          deviceDetails_ = null;
        }
        return deviceDetailsBuilder_;
      }

      private com.google.protobuf.ByteString guardData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes guard_data = 10 [(.description) = "steam guard data for client login"];</code>
       * @return Whether the guardData field is set.
       */
      @java.lang.Override
      public boolean hasGuardData() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional bytes guard_data = 10 [(.description) = "steam guard data for client login"];</code>
       * @return The guardData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGuardData() {
        return guardData_;
      }
      /**
       * <code>optional bytes guard_data = 10 [(.description) = "steam guard data for client login"];</code>
       * @param value The guardData to set.
       * @return This builder for chaining.
       */
      public Builder setGuardData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        guardData_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes guard_data = 10 [(.description) = "steam guard data for client login"];</code>
       * @return This builder for chaining.
       */
      public Builder clearGuardData() {
        bitField0_ = (bitField0_ & ~0x00000200);
        guardData_ = getDefaultInstance().getGuardData();
        onChanged();
        return this;
      }

      private int language_ ;
      /**
       * <code>optional uint32 language = 11;</code>
       * @return Whether the language field is set.
       */
      @java.lang.Override
      public boolean hasLanguage() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>optional uint32 language = 11;</code>
       * @return The language.
       */
      @java.lang.Override
      public int getLanguage() {
        return language_;
      }
      /**
       * <code>optional uint32 language = 11;</code>
       * @param value The language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguage(int value) {

        language_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 language = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguage() {
        bitField0_ = (bitField0_ & ~0x00000400);
        language_ = 0;
        onChanged();
        return this;
      }

      private int qosLevel_ = 2;
      /**
       * <code>optional int32 qos_level = 12 [default = 2, (.description) = "[ENetQOSLevel] client-specified priority for this auth attempt"];</code>
       * @return Whether the qosLevel field is set.
       */
      @java.lang.Override
      public boolean hasQosLevel() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>optional int32 qos_level = 12 [default = 2, (.description) = "[ENetQOSLevel] client-specified priority for this auth attempt"];</code>
       * @return The qosLevel.
       */
      @java.lang.Override
      public int getQosLevel() {
        return qosLevel_;
      }
      /**
       * <code>optional int32 qos_level = 12 [default = 2, (.description) = "[ENetQOSLevel] client-specified priority for this auth attempt"];</code>
       * @param value The qosLevel to set.
       * @return This builder for chaining.
       */
      public Builder setQosLevel(int value) {

        qosLevel_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 qos_level = 12 [default = 2, (.description) = "[ENetQOSLevel] client-specified priority for this auth attempt"];</code>
       * @return This builder for chaining.
       */
      public Builder clearQosLevel() {
        bitField0_ = (bitField0_ & ~0x00000800);
        qosLevel_ = 2;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData)
    }

    // @@protoc_insertion_point(class_scope:CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData)
    private static final Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData();
    }

    public static Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData>
        PARSER = new com.google.protobuf.AbstractParser<CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData>() {
      @java.lang.Override
      public CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Custom.CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014custom.proto\032\030steammessages_base.proto" +
      "\032,steammessages_unified_base.steamclient" +
      ".proto\032\013enums.proto\032$steammessages_auth." +
      "steamclient.proto\"\222\007\nFCAuthentication_Be" +
      "ginAuthSessionViaCredentials_Request_Bin" +
      "aryGuardData\022\034\n\024device_friendly_name\030\001 \001" +
      "(\t\022\024\n\014account_name\030\002 \001(\t\022C\n\022encrypted_pa" +
      "ssword\030\003 \001(\tB\'\202\265\030#password, RSA encrypte" +
      "d client side\022C\n\024encryption_timestamp\030\004 " +
      "\001(\004B%\202\265\030!timestamp to map to a key - STi" +
      "me\022&\n\016remember_login\030\005 \001(\010B\016\202\265\030\ndeprecat" +
      "ed\022P\n\rplatform_type\030\006 \001(\0162\027.EAuthTokenPl" +
      "atformType: k_EAuthTokenPlatformType_Unk" +
      "nown\022\217\001\n\013persistence\030\007 \001(\0162\024.ESessionPer" +
      "sistence: k_ESessionPersistence_Persiste" +
      "ntBB\202\265\030>whether we are requesting a pers" +
      "istent or an ephemeral session\022]\n\nwebsit" +
      "e_id\030\010 \001(\t:\007UnknownB@\202\265\030<(EMachineAuthWe" +
      "bDomain) identifier of client requesting" +
      " auth\022x\n\016device_details\030\t \001(\0132\036.CAuthent" +
      "ication_DeviceDetailsB@\202\265\030<User-supplied" +
      " details about the device attempting to " +
      "sign in\0229\n\nguard_data\030\n \001(\014B%\202\265\030!steam g" +
      "uard data for client login\022\020\n\010language\030\013" +
      " \001(\r\022X\n\tqos_level\030\014 \001(\005:\0012BB\202\265\030>[ENetQOS" +
      "Level] client-specified priority for thi" +
      "s auth attemptB\003\200\001\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SteammessagesBase.getDescriptor(),
          SteammessagesUnifiedBaseSteamclient.getDescriptor(),
          Enums.getDescriptor(),
          SteammessagesAuthSteamclient.getDescriptor(),
        });
    internal_static_CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CAuthentication_BeginAuthSessionViaCredentials_Request_BinaryGuardData_descriptor,
        new java.lang.String[] { "DeviceFriendlyName", "AccountName", "EncryptedPassword", "EncryptionTimestamp", "RememberLogin", "PlatformType", "Persistence", "WebsiteId", "DeviceDetails", "GuardData", "Language", "QosLevel", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(SteammessagesUnifiedBaseSteamclient.description);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    SteammessagesBase.getDescriptor();
    SteammessagesUnifiedBaseSteamclient.getDescriptor();
    Enums.getDescriptor();
    SteammessagesAuthSteamclient.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
